CREATE TABLE TEAM
(
    ID   NUMBER(8, 0) NOT NULL,
    NAME VARCHAR2(30 BYTE),
    DATE_CREATED TIMESTAMP(8),
    CONSTRAINT TEAM_PK PRIMARY KEY (ID),
);

AFTER TABLE STAFF
(
    ID   NUMBER(8, 0) NOT NULL,
    NAME VARCHAR(100 BYTE) NOT NULL,
    PHONE_NUMBER      VARCHAR(20 BYTE),
    EMAIL VARCHAR2 (100 BYTE),
    TEAM_ID       NUMBER(8, 0) NOT NULL,
    DATE_CREATED  TIMESTAMP(6),
    IMAGE_PATH VARCHAR(200 BYTE),
    CONSTRAINT STAFF_PK PRIMARY KEY (ID),
    CONSTRAINT STAFF_FK1 FOREIGN KEY (TEAM_ID) REFERENCES TEAM (ID)
);

create sequence STAFF_SEQ MINVALUE 1 MAXVALUE 9999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20
    NOORDER NOCYCLE ;


